style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/MorpheusNephew/td-ameritrade-models
options:
  commits:
    filters:
      Type:
        - Feat
        - Fix
        - Perf
        - Refactor
  commit_groups:
    title_maps:
      Feat: Features
      Fix: Bug Fixes
      Perf: Performance Improvements
      Refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
